//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppHero
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hero()
        {
            this.Sacoche = new HashSet<Sacoche>();
        }
    
        public string nom { get; set; }
        public string prenom { get; set; }
        public string specialite { get; set; }
        public string classHero { get; set; }
        public Nullable<int> lvl { get; set; }
        public Nullable<int> puissance { get; set; }
        public Nullable<int> missionReussi { get; set; }
        public Nullable<int> reputation { get; set; }
        public int id_hero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sacoche> Sacoche { get; set; }
    }
}
